### ISSUE TITLE
Fixit cli not working with python 3.7.0 

### ISSUE THREAD

**Issue by acharles7** [Instagram/Fixit#121]
When running `python -m fixit.cli.run_rules --help` gives 
```python
@dataclass(frozen=True, eq=False, unsafe_hash=False)
TypeError: dataclass() got an unexpected keyword argument 'unsafe_hash'
```
In Python 3.7.0 there is no `unsafe_hash` parameter of data classes
So, In Fixit module, we have to explicitly specify that this package work with python >= 3.7.8 because the implementation of `unsafe_hash` available in Python >= 3.7.8

or removing `unsafe_hash=False` will remove this error. In such case, We have to figure out a way to replace `unsafe_hash`

**Comment by jimmylai** [comment]
I didn't find unsafe_hash used in Fixit.
It's probably used in LibCST.
https://github.com/Instagram/LibCST/blob/7ca738bf3964ac48ebb36b1b362153c87c29a706/libcst/codegen/gen_matcher_classes.py#L545
Change this will take some efforts and it's probably not worth it.

We currently run tests in Python 3.6, 3.7, 3.8 in CI builds.
Ideally, the user of each version should try to keep upgrade to newer minor version to get new feature and security fixes.
So, this looks like a minor issue to me.

**Comment by acharles7** [comment]
Yes, you're totally right.

**Comment by jimmylai** [comment]
Closing this for now since this is a minor issue and doesn't worth fixing it.
